namespace SFTPReaderTimer.Models
{
    public class Detail
    {
        public string acct_promo_acctnum { get; set; }
        public string acct_promo_amt { get; set; }
        public string acct_promo_code { get; set; }
        public string alt_category_cd { get; set; }
        public string attribute_id { get; set; }
        public string base_type_code { get; set; }
        public string branch_cd { get; set; }
        public string business_rule_id { get; set; }
        public string category_cd { get; set; }
        public string class_cd { get; set; }
        public string clerk { get; set; }
        public string company_cd { get; set; }
        public string cost { get; set; }
        public string cust_acct_type { get; set; }
        public string cust_company { get; set; }
        public string cust_currency { get; set; }
        public string cust_first { get; set; }
        public string cust_last { get; set; }
        public string cust_location { get; set; }
        public string cust_mi { get; set; }
        public string cust_number { get; set; }
        public string group_id { get; set; }
        public string hierarchy_type_id { get; set; }
        public string is_allow_discount { get; set; }
        public string is_local { get; set; }
        public string is_lookup { get; set; }
        public string is_manual { get; set; }
        public string is_own_line { get; set; }
        public string is_price_prompt { get; set; }
        public string is_promo_event { get; set; }
        public string is_pwd { get; set; }
        public string is_sc { get; set; }
        public string is_scanned { get; set; }
        public string is_take_item { get; set; }
        public string is_vat { get; set; }
        public string is_vat_zero { get; set; }
        public string item_code { get; set; }
        public string item_description { get; set; }
        public string net_retail { get; set; }
        public string order_num { get; set; }
        public string orig_retail { get; set; }
        public string orig_zero_rated { get; set; }
        public string pay_promo_acctnum { get; set; }
        public string pay_promo_amt { get; set; }
        public string pay_promo_code { get; set; }
        public string price_overide { get; set; }
        public string promo_amt { get; set; }
        public string promo_auth { get; set; }
        public string promo_calc { get; set; }
        public string promo_code { get; set; }
        public string promo_desc { get; set; }
        public string promo_max { get; set; }
        public string promo_min { get; set; }
        public string promo_seq { get; set; }
        public string promo_type { get; set; }
        public string promo_value { get; set; }
        public string qty { get; set; }
        public string reason_code { get; set; }
        public string register_num { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string retail { get; set; }
        public string return_amount { get; set; }
        public string return_branch_cd { get; set; }
        public string return_company_cd { get; set; }
        public string return_qty { get; set; }
        public string return_register_num { get; set; }
        public string return_seq { get; set; }
        public string return_sys_trans_num { get; set; }
        public string sell_uom { get; set; }
        public string seq_num { get; set; }
        public string subcat_cd { get; set; }
        public string subclass_cd { get; set; }
        public string sys_trans_num { get; set; }
        public string tax1 { get; set; }
        public string tax2 { get; set; }
        public string tax_cd { get; set; }
        public string tax_desc { get; set; }
        public string tax_max { get; set; }
        public string tax_min { get; set; }
        public string tax_pct { get; set; }
        public string tax_value { get; set; }
        public string upc_code { get; set; }
        public string upc_qty { get; set; }
        public string upc_uom { get; set; }
        public string vat_code { get; set; }
        public string version_id { get; set; }
    }
}