namespace SFTPReaderTimer.Models
{
    public class Header
    {
        public string account_number { get; set; }
        public string acct_type_code { get; set; }
        public string attribute_id { get; set; }
        public string auth_manager { get; set; }
        public string branch_cd { get; set; }
        public string business_rule_id { get; set; }
        public string cashier { get; set; }
        public string cashier_shift { get; set; }
        public string cd_addr { get; set; }
        public string cd_business_style { get; set; }
        public string cd_first_name { get; set; }
        public string cd_last_name { get; set; }
        public string cd_mi { get; set; }
        public string cd_mobilenumber { get; set; }
        public string cd_scpwdid { get; set; }
        public string cd_tin { get; set; }
        public string cd_validity_date { get; set; }
        public string company_cd { get; set; }
        public string company_id { get; set; }
        public string cur_epurse { get; set; }
        public string cur_points { get; set; }
        public string delivery { get; set; }
        public string division_id { get; set; }
        public string end_txn_time { get; set; }
        public string first_name { get; set; }
        public string group_id { get; set; }
        public string hierarchy_type_id { get; set; }
        public string is_cancel { get; set; }
        public string is_cook_date { get; set; }
        public string is_cook_time { get; set; }
        public string is_cook_user { get; set; }
        public string is_export { get; set; }
        public string is_layaway { get; set; }
        public string is_pac { get; set; }
        public string is_polled { get; set; }
        public string is_process { get; set; }
        public string is_reprint { get; set; }
        public string is_settled { get; set; }
        public string is_suspend { get; set; }
        public string is_sync { get; set; }
        public string is_uploaded { get; set; }
        public string is_void { get; set; }
        public string is_zero_rated { get; set; }
        public string last_name { get; set; }
        public string lay_stamp { get; set; }
        public string logical_date { get; set; }
        public string memberid { get; set; }
        public string membername { get; set; }
        public string middle_initial { get; set; }
        public string order_num { get; set; }
        public string paytype { get; set; }
        public string pos_serial_num { get; set; }
        public string posorderid { get; set; }
        public string prev_epurse { get; set; }
        public string prev_points { get; set; }
        public string pshopper { get; set; }
        public string ref_trans_num { get; set; }
        public string register_num { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string reprint_cnt { get; set; }
        public string reprint_mgr { get; set; }
        public string sclerk { get; set; }
        public string start_txn_time { get; set; }
        public string sys_trans_num { get; set; }
        public string trans_alt_code { get; set; }
        public string trans_cancel { get; set; }
        public string trans_cd { get; set; }
        public string trans_date { get; set; }
        public string trans_deposit { get; set; }
        public string trans_desc { get; set; }
        public string trans_flag_account { get; set; }
        public string trans_flag_cancel { get; set; }
        public string trans_flag_deposit { get; set; }
        public string trans_flag_layaway { get; set; }
        public string trans_flag_pac { get; set; }
        public string trans_flag_return { get; set; }
        public string trans_flag_zero_rated { get; set; }
        public string trans_max { get; set; }
        public string trans_min { get; set; }
        public string trans_num { get; set; }
        public string trans_time { get; set; }
        public string unserve_mgr { get; set; }
        public string version_id { get; set; }
        public string void_remark1 { get; set; }
        public string void_remark2 { get; set; }
        public string void_remark3 { get; set; }
        public string warehouse_id { get; set; }
    }
}