namespace SFTPReaderTimer.Models
{
    public class Payment
    {
        public string acct_num { get; set; }
        public string acct_type_code { get; set; }
        public string alt_tender_code { get; set; }
        public string amount_tendered { get; set; }
        public string amt_balance { get; set; }
        public string amt_limit { get; set; }
        public string amt_original { get; set; }
        public string approval { get; set; }
        public string approved_by { get; set; }
        public string auth_manager { get; set; }
        public string bank_code { get; set; }
        public string branch_cd { get; set; }
        public string c3_apprcode { get; set; }
        public string c3_batchid { get; set; }
        public string c3_date { get; set; }
        public string c3_merchid { get; set; }
        public string c3_nii { get; set; }
        public string c3_respcode { get; set; }
        public string c3_resptxt { get; set; }
        public string c3_retrefno { get; set; }
        public string c3_systrcno { get; set; }
        public string c3_time { get; set; }
        public string c3_track1 { get; set; }
        public string c3_track2 { get; set; }
        public string c3_trancode { get; set; }
        public string change_action { get; set; }
        public string change_amount { get; set; }
        public string change_cd { get; set; }
        public string change_local_rate { get; set; }
        public string change_rate { get; set; }
        public string company { get; set; }
        public string company_cd { get; set; }
        public string conv_change_amount { get; set; }
        public string conv_gc_change_amount { get; set; }
        public string conv_pay_amount { get; set; }
        public string conv_pay_amount_due { get; set; }
        public string conv_tendered { get; set; }
        public string currency_action { get; set; }
        public string currency_cd { get; set; }
        public string currency_local_rate { get; set; }
        public string currency_rate { get; set; }
        public string date_paid { get; set; }
        public string discount_acct_type_code { get; set; }
        public string discount_customer_id { get; set; }
        public string first_name { get; set; }
        public string gc_change_amount { get; set; }
        public string is_card_connect { get; set; }
        public string is_cash { get; set; }
        public string is_cashfund { get; set; }
        public string is_cashgate_bill { get; set; }
        public string is_cashgate_pay { get; set; }
        public string is_change { get; set; }
        public string is_charge { get; set; }
        public string is_check { get; set; }
        public string is_creditcard { get; set; }
        public string is_debitcard { get; set; }
        public string is_declare { get; set; }
        public string is_default { get; set; }
        public string is_deposit { get; set; }
        public string is_display_total { get; set; }
        public string is_egc { get; set; }
        public string is_epurse { get; set; }
        public string is_ewallet { get; set; }
        public string is_expire { get; set; }
        public string is_garbage { get; set; }
        public string is_gc { get; set; }
        public string is_manual { get; set; }
        public string is_refund_type { get; set; }
        public string is_res { get; set; }
        public string is_rma { get; set; }
        public string is_rmes { get; set; }
        public string is_takeout { get; set; }
        public string is_validate { get; set; }
        public string is_validation_space { get; set; }
        public string last_name { get; set; }
        public string max_amount { get; set; }
        public string max_change { get; set; }
        public string max_refund { get; set; }
        public string mi { get; set; }
        public string min_amount { get; set; }
        public string new_payment { get; set; }
        public string pay_amount { get; set; }
        public string pay_amount_due { get; set; }
        public string pay_seq { get; set; }
        public string promo_amt { get; set; }
        public string promo_calc { get; set; }
        public string promo_code { get; set; }
        public string promo_desc { get; set; }
        public string promo_max { get; set; }
        public string promo_min { get; set; }
        public string promo_type { get; set; }
        public string promo_value { get; set; }
        public string ref_num { get; set; }
        public string register_num { get; set; }
        public string sys_trans_num { get; set; }
        public string tender_code { get; set; }
        public string tender_desc { get; set; }
        public string tender_screen { get; set; }
        public string tender_type_code { get; set; }
        public string terminal { get; set; }
    }
}